// ============================================================
//  Mermelada Project — data.js
//  Glosario médico de enfermería
//  Fuente de verdad. Para agregar términos en producción,
//  usa el panel admin (guarda en localStorage) y luego
//  exporta aquí cuando estés listo para hacer commit.
// ============================================================

const CATEGORIAS = {
  anatomia:       "Anatomía general",
  cardiovascular: "Sistema cardiovascular",
  respiratorio:   "Sistema respiratorio",
  nervioso:       "Sistema nervioso",
  digestivo:      "Sistema digestivo",
  musculo:        "Sistema musculoesquelético",
  inmune:         "Sistema inmune",
  renal:          "Sistema renal",
  endocrino:      "Sistema endocrino",
  farmacologia:   "Farmacología básica",
  signos:         "Signos vitales y valoración",
  procedimientos: "Procedimientos de enfermería",
  patologia:      "Patología y enfermedad",
};

const diccionarioMedico = {

  // ── ANATOMÍA GENERAL ──────────────────────────────────────
  celula: {
    titulo: "Célula",
    categoria: "anatomia",
    definicion: "Unidad estructural y funcional básica de todos los seres vivos. Es la mínima expresión de vida capaz de llevar a cabo procesos metabólicos por sí misma.",
    ejemplo: "Las células musculares (miocitos) se contraen para generar movimiento.",
    relacionadas: ["tejido", "organelo", "ADN", "membrana-celular"],
  },
  tejido: {
    titulo: "Tejido",
    categoria: "anatomia",
    definicion: "Conjunto de células similares que trabajan coordinadamente para realizar una función específica. Existen cuatro tipos principales: epitelial, conectivo, muscular y nervioso.",
    ejemplo: "El tejido epitelial recubre la superficie de la piel y las mucosas.",
    relacionadas: ["celula", "organo"],
  },
  organo: {
    titulo: "Órgano",
    categoria: "anatomia",
    definicion: "Estructura formada por varios tejidos organizados para cumplir una función determinada dentro del organismo.",
    ejemplo: "El corazón es un órgano compuesto principalmente por tejido muscular cardíaco.",
    relacionadas: ["tejido", "sistema"],
  },
  organelo: {
    titulo: "Organelo",
    categoria: "anatomia",
    definicion: "Estructura subcelular especializada que realiza funciones específicas dentro de la célula, análogo a los órganos en el cuerpo.",
    ejemplo: "Las mitocondrias son organelos encargados de producir energía en forma de ATP.",
    relacionadas: ["celula", "mitocondria"],
  },
  mitocondria: {
    titulo: "Mitocondria",
    categoria: "anatomia",
    definicion: "Organelo celular encargado de la respiración celular aeróbica. Produce la mayor parte del ATP que usa la célula.",
    ejemplo: "Las células musculares tienen alta densidad de mitocondrias por su gran demanda energética.",
    relacionadas: ["organelo", "celula"],
  },
  "membrana-celular": {
    titulo: "Membrana celular",
    categoria: "anatomia",
    definicion: "Estructura de doble capa lipídica que delimita la célula y regula el paso de sustancias entre el interior y el exterior celular.",
    ejemplo: "La membrana celular controla qué nutrientes entran y qué desechos salen de la célula.",
    relacionadas: ["celula", "difusion", "osmosis"],
  },
  difusion: {
    titulo: "Difusión",
    categoria: "anatomia",
    definicion: "Proceso pasivo por el cual las moléculas se desplazan desde una zona de mayor concentración hacia una de menor concentración, sin gasto de energía.",
    ejemplo: "El oxígeno difunde desde los alvéolos pulmonares hacia la sangre.",
    relacionadas: ["osmosis", "membrana-celular"],
  },
  osmosis: {
    titulo: "Ósmosis",
    categoria: "anatomia",
    definicion: "Movimiento pasivo de agua a través de una membrana semipermeable desde una zona de menor concentración de solutos hacia una de mayor concentración.",
    ejemplo: "Cuando se administra suero hipertónico, el agua sale de las células por ósmosis.",
    relacionadas: ["difusion", "membrana-celular"],
  },
  homeostasis: {
    titulo: "Homeostasis",
    categoria: "anatomia",
    definicion: "Capacidad del organismo para mantener condiciones internas relativamente estables (temperatura, pH, glucosa, etc.) frente a cambios del entorno.",
    ejemplo: "La regulación de la temperatura corporal a 37 °C es un ejemplo clásico de homeostasis.",
    relacionadas: ["metabolismo", "retroalimentacion"],
  },
  metabolismo: {
    titulo: "Metabolismo",
    categoria: "anatomia",
    definicion: "Conjunto de reacciones químicas que ocurren en el organismo para obtener energía, construir moléculas y mantener las funciones vitales.",
    ejemplo: "Un paciente en ayuno utiliza el metabolismo de grasas como fuente de energía.",
    relacionadas: ["homeostasis", "catabolismo", "anabolismo"],
  },
  catabolismo: {
    titulo: "Catabolismo",
    categoria: "anatomia",
    definicion: "Fase del metabolismo en la que moléculas complejas se descomponen en moléculas más simples, liberando energía.",
    ejemplo: "La degradación de glucosa en glucólisis es un proceso catabólico.",
    relacionadas: ["metabolismo", "anabolismo"],
  },
  anabolismo: {
    titulo: "Anabolismo",
    categoria: "anatomia",
    definicion: "Fase del metabolismo en la que se construyen moléculas complejas a partir de moléculas simples, con consumo de energía.",
    ejemplo: "La síntesis de proteínas musculares tras el ejercicio es un proceso anabólico.",
    relacionadas: ["metabolismo", "catabolismo"],
  },
  ADN: {
    titulo: "ADN",
    categoria: "anatomia",
    definicion: "Ácido desoxirribonucleico. Molécula que contiene la información genética del organismo, organizada en genes. Se encuentra en el núcleo de la célula.",
    ejemplo: "Cada célula del cuerpo humano contiene el mismo ADN excepto los glóbulos rojos maduros.",
    relacionadas: ["celula", "gen", "cromosoma"],
  },

  // ── SISTEMA CARDIOVASCULAR ────────────────────────────────
  corazon: {
    titulo: "Corazón",
    categoria: "cardiovascular",
    definicion: "Órgano muscular hueco que actúa como bomba para impulsar la sangre a través del sistema circulatorio. Está dividido en cuatro cámaras: dos aurículas y dos ventrículos.",
    ejemplo: "El corazón de un adulto en reposo late entre 60 y 100 veces por minuto.",
    relacionadas: ["frecuencia-cardiaca", "arteria", "vena", "sistole", "diastole"],
  },
  arteria: {
    titulo: "Arteria",
    categoria: "cardiovascular",
    definicion: "Vaso sanguíneo de paredes gruesas y elásticas que conduce sangre oxigenada desde el corazón hacia los tejidos (excepto las arterias pulmonares).",
    ejemplo: "La arteria aorta es la más grande del cuerpo y sale directamente del ventrículo izquierdo.",
    relacionadas: ["vena", "capilar", "corazon", "pulso"],
  },
  vena: {
    titulo: "Vena",
    categoria: "cardiovascular",
    definicion: "Vaso sanguíneo que transporta sangre de regreso al corazón. Poseen válvulas que evitan el reflujo de la sangre.",
    ejemplo: "Las venas yugulares retornan la sangre de la cabeza hacia el corazón.",
    relacionadas: ["arteria", "capilar", "corazon"],
  },
  capilar: {
    titulo: "Capilar",
    categoria: "cardiovascular",
    definicion: "Vaso sanguíneo microscópico que conecta arteriolas con vénulas. Es el sitio donde ocurre el intercambio de gases, nutrientes y desechos entre la sangre y los tejidos.",
    ejemplo: "El intercambio de oxígeno y CO₂ en los pulmones ocurre a nivel de capilares alveolares.",
    relacionadas: ["arteria", "vena", "difusion"],
  },
  sistole: {
    titulo: "Sístole",
    categoria: "cardiovascular",
    definicion: "Fase de contracción del músculo cardíaco durante la cual los ventrículos expulsan sangre hacia las arterias.",
    ejemplo: "El valor superior de la presión arterial (120 mmHg) corresponde a la presión sistólica.",
    relacionadas: ["diastole", "presion-arterial", "corazon"],
  },
  diastole: {
    titulo: "Diástole",
    categoria: "cardiovascular",
    definicion: "Fase de relajación del músculo cardíaco durante la cual los ventrículos se llenan de sangre proveniente de las aurículas.",
    ejemplo: "El valor inferior de la presión arterial (80 mmHg) corresponde a la presión diastólica.",
    relacionadas: ["sistole", "presion-arterial", "corazon"],
  },
  "frecuencia-cardiaca": {
    titulo: "Frecuencia cardíaca",
    categoria: "cardiovascular",
    definicion: "Número de veces que el corazón se contrae por minuto. El rango normal en adultos en reposo es de 60 a 100 latidos por minuto.",
    ejemplo: "Una frecuencia cardíaca de 45 lpm en reposo puede indicar bradicardia.",
    relacionadas: ["taquicardia", "bradicardia", "pulso", "corazon"],
  },
  taquicardia: {
    titulo: "Taquicardia",
    categoria: "cardiovascular",
    definicion: "Frecuencia cardíaca superior a 100 latidos por minuto en adultos. Puede ser fisiológica (ejercicio, estrés) o patológica.",
    ejemplo: "El paciente presentó taquicardia de 130 lpm tras el esfuerzo físico intenso.",
    relacionadas: ["bradicardia", "frecuencia-cardiaca", "arritmia"],
  },
  bradicardia: {
    titulo: "Bradicardia",
    categoria: "cardiovascular",
    definicion: "Frecuencia cardíaca inferior a 60 latidos por minuto en adultos. Puede ser normal en atletas o indicar una patología.",
    ejemplo: "Un corredor de fondo puede tener bradicardia fisiológica de 45 lpm.",
    relacionadas: ["taquicardia", "frecuencia-cardiaca", "arritmia"],
  },
  arritmia: {
    titulo: "Arritmia",
    categoria: "cardiovascular",
    definicion: "Alteración del ritmo cardíaco normal. Puede ser por frecuencia (muy rápida o muy lenta) o por irregularidad en los latidos.",
    ejemplo: "La fibrilación auricular es la arritmia sostenida más común en la práctica clínica.",
    relacionadas: ["taquicardia", "bradicardia", "corazon"],
  },
  "presion-arterial": {
    titulo: "Presión arterial",
    categoria: "cardiovascular",
    definicion: "Fuerza que ejerce la sangre contra las paredes de las arterias. Se expresa en mmHg con dos valores: sistólica/diastólica. El rango normal es 120/80 mmHg.",
    ejemplo: "Una presión de 150/95 mmHg en dos mediciones separadas puede indicar hipertensión.",
    relacionadas: ["sistole", "diastole", "hipertension", "hipotension"],
  },
  hipertension: {
    titulo: "Hipertensión",
    categoria: "cardiovascular",
    definicion: "Presión arterial crónicamente elevada, con valores iguales o superiores a 140/90 mmHg. Es un factor de riesgo cardiovascular mayor.",
    ejemplo: "La hipertensión no controlada aumenta el riesgo de infarto y accidente cerebrovascular.",
    relacionadas: ["presion-arterial", "hipotension"],
  },
  hipotension: {
    titulo: "Hipotensión",
    categoria: "cardiovascular",
    definicion: "Presión arterial por debajo de 90/60 mmHg. Puede causar mareos, síncope y compromiso de la perfusión orgánica.",
    ejemplo: "La hipotensión ortostática ocurre al levantarse bruscamente y puede causar desmayos.",
    relacionadas: ["presion-arterial", "hipertension", "sincope"],
  },
  pulso: {
    titulo: "Pulso",
    categoria: "cardiovascular",
    definicion: "Expansión rítmica de una arteria producida por el paso de la onda de presión generada por cada latido cardíaco. Se palpa en puntos accesibles como la muñeca o el cuello.",
    ejemplo: "El pulso radial se toma en la muñeca y es el sitio más común para medir la frecuencia cardíaca.",
    relacionadas: ["frecuencia-cardiaca", "arteria"],
  },

  // ── SISTEMA RESPIRATORIO ──────────────────────────────────
  pulmon: {
    titulo: "Pulmón",
    categoria: "respiratorio",
    definicion: "Órgano principal del sistema respiratorio, encargado del intercambio gaseoso entre el aire y la sangre. El pulmón derecho tiene tres lóbulos y el izquierdo dos.",
    ejemplo: "En una neumonía, los alvéolos pulmonares se llenan de líquido inflamatorio.",
    relacionadas: ["alveolo", "bronquio", "frecuencia-respiratoria"],
  },
  alveolo: {
    titulo: "Alvéolo",
    categoria: "respiratorio",
    definicion: "Pequeño saco de aire al final de los bronquiolos donde ocurre el intercambio de oxígeno y dióxido de carbono entre el aire y la sangre.",
    ejemplo: "Un adulto tiene aproximadamente 300 millones de alvéolos en ambos pulmones.",
    relacionadas: ["pulmon", "difusion", "capilares"],
  },
  bronquio: {
    titulo: "Bronquio",
    categoria: "respiratorio",
    definicion: "Conducto que lleva el aire desde la tráquea hasta los pulmones. Se divide en bronquio derecho e izquierdo, que luego se ramifican en bronquiolos.",
    ejemplo: "En el asma, los bronquios se inflaman y se estrechan, dificultando la respiración.",
    relacionadas: ["pulmon", "alveolo", "traquea"],
  },
  traquea: {
    titulo: "Tráquea",
    categoria: "respiratorio",
    definicion: "Tubo cartilaginoso que conecta la laringe con los bronquios principales. Conduce el aire hacia y desde los pulmones.",
    ejemplo: "Una obstrucción de la tráquea es una emergencia médica que requiere acción inmediata.",
    relacionadas: ["bronquio", "laringe"],
  },
  "frecuencia-respiratoria": {
    titulo: "Frecuencia respiratoria",
    categoria: "respiratorio",
    definicion: "Número de ciclos respiratorios (inspiración + espiración) por minuto. El rango normal en adultos es de 12 a 20 respiraciones por minuto.",
    ejemplo: "Una frecuencia respiratoria de 28 rpm puede indicar taquipnea por esfuerzo o patología.",
    relacionadas: ["taquipnea", "bradipnea", "saturacion"],
  },
  taquipnea: {
    titulo: "Taquipnea",
    categoria: "respiratorio",
    definicion: "Frecuencia respiratoria superior a 20 respiraciones por minuto en adultos. Puede ser signo de hipoxia, ansiedad, fiebre o patología pulmonar.",
    ejemplo: "El paciente presentó taquipnea de 28 rpm y saturación del 91%.",
    relacionadas: ["frecuencia-respiratoria", "bradipnea", "disnea"],
  },
  bradipnea: {
    titulo: "Bradipnea",
    categoria: "respiratorio",
    definicion: "Frecuencia respiratoria inferior a 12 respiraciones por minuto. Puede indicar depresión del sistema nervioso central, intoxicación por opiáceos u otras causas.",
    ejemplo: "La sobredosis de morfina puede provocar bradipnea severa.",
    relacionadas: ["frecuencia-respiratoria", "taquipnea"],
  },
  disnea: {
    titulo: "Disnea",
    categoria: "respiratorio",
    definicion: "Sensación subjetiva de dificultad para respirar o falta de aire. Es un síntoma, no un diagnóstico, y puede tener múltiples causas.",
    ejemplo: "El paciente refiere disnea de esfuerzo que le impide subir escaleras.",
    relacionadas: ["taquipnea", "saturacion", "pulmon"],
  },
  saturacion: {
    titulo: "Saturación de oxígeno (SpO₂)",
    categoria: "respiratorio",
    definicion: "Porcentaje de hemoglobina en la sangre que está unida a oxígeno. Se mide con pulsioxímetro. El rango normal es del 95 al 100%.",
    ejemplo: "Una saturación menor al 90% indica hipoxemia y requiere intervención inmediata.",
    relacionadas: ["hemoglobina", "disnea", "frecuencia-respiratoria"],
  },

  // ── SISTEMA NERVIOSO ──────────────────────────────────────
  neurona: {
    titulo: "Neurona",
    categoria: "nervioso",
    definicion: "Célula fundamental del sistema nervioso. Transmite señales eléctricas y químicas. Consta de cuerpo celular, dendritas y axón.",
    ejemplo: "Una neurona motora en la médula espinal puede tener un axón de más de un metro de largo.",
    relacionadas: ["sinapsis", "axon", "cerebro"],
  },
  sinapsis: {
    titulo: "Sinapsis",
    categoria: "nervioso",
    definicion: "Unión funcional entre dos neuronas o entre una neurona y una célula efectora, a través de la cual se transmite el impulso nervioso mediante neurotransmisores.",
    ejemplo: "La acetilcolina es el neurotransmisor que actúa en la sinapsis neuromuscular.",
    relacionadas: ["neurona", "neurotransmisor"],
  },
  neurotransmisor: {
    titulo: "Neurotransmisor",
    categoria: "nervioso",
    definicion: "Sustancia química liberada en la sinapsis que transmite señales entre neuronas o entre neuronas y células efectoras.",
    ejemplo: "La serotonina es un neurotransmisor asociado con la regulación del estado de ánimo.",
    relacionadas: ["sinapsis", "neurona"],
  },
  cerebro: {
    titulo: "Cerebro",
    categoria: "nervioso",
    definicion: "Órgano principal del sistema nervioso central. Controla funciones cognitivas, motoras, sensoriales y vegetativas. Se divide en hemisferio derecho e izquierdo.",
    ejemplo: "El área de Broca en el hemisferio izquierdo controla la producción del lenguaje.",
    relacionadas: ["neurona", "medula-espinal"],
  },
  "medula-espinal": {
    titulo: "Médula espinal",
    categoria: "nervioso",
    definicion: "Estructura del sistema nervioso central que recorre el canal vertebral. Conduce impulsos entre el cerebro y el resto del cuerpo y coordina reflejos.",
    ejemplo: "Una lesión en la médula espinal cervical puede causar tetraplejia.",
    relacionadas: ["cerebro", "neurona", "reflejo"],
  },
  reflejo: {
    titulo: "Reflejo",
    categoria: "nervioso",
    definicion: "Respuesta motora automática e involuntaria a un estímulo específico, mediada por la médula espinal sin intervención consciente del cerebro.",
    ejemplo: "El reflejo rotuliano (golpe en la rodilla) es una prueba básica de la integridad nerviosa.",
    relacionadas: ["medula-espinal", "neurona"],
  },
  sincope: {
    titulo: "Síncope",
    categoria: "nervioso",
    definicion: "Pérdida transitoria del conocimiento y del tono postural debida a una disminución temporal del flujo sanguíneo cerebral.",
    ejemplo: "El síncope vasovagal puede ocurrir al ver sangre o ante una emoción intensa.",
    relacionadas: ["hipotension", "cerebro"],
  },

  // ── FARMACOLOGÍA BÁSICA ───────────────────────────────────
  farmaco: {
    titulo: "Fármaco",
    categoria: "farmacologia",
    definicion: "Sustancia de origen natural o sintético que, al interactuar con el organismo, produce un efecto biológico que puede usarse con fines terapéuticos, preventivos o diagnósticos.",
    ejemplo: "El paracetamol es un fármaco analgésico y antipirético de uso muy común.",
    relacionadas: ["dosis", "via-administracion", "efecto-adverso"],
  },
  dosis: {
    titulo: "Dosis",
    categoria: "farmacologia",
    definicion: "Cantidad de un fármaco que se administra en un momento determinado para obtener el efecto terapéutico deseado sin causar toxicidad.",
    ejemplo: "La dosis terapéutica de paracetamol en adultos es de 500-1000 mg cada 6-8 horas.",
    relacionadas: ["farmaco", "sobredosis", "via-administracion"],
  },
  sobredosis: {
    titulo: "Sobredosis",
    categoria: "farmacologia",
    definicion: "Administración de una cantidad de fármaco o sustancia que supera el límite seguro, produciendo efectos tóxicos en el organismo.",
    ejemplo: "Una sobredosis de paracetamol puede causar insuficiencia hepática grave.",
    relacionadas: ["dosis", "farmaco", "efecto-adverso"],
  },
  "via-administracion": {
    titulo: "Vía de administración",
    categoria: "farmacologia",
    definicion: "Ruta por la cual un fármaco es introducido en el organismo. Las principales son: oral, intravenosa, intramuscular, subcutánea, tópica e inhalatoria.",
    ejemplo: "La vía intravenosa produce un efecto más rápido que la vía oral porque evita el primer paso hepático.",
    relacionadas: ["farmaco", "dosis"],
  },
  "efecto-adverso": {
    titulo: "Efecto adverso",
    categoria: "farmacologia",
    definicion: "Reacción no deseada y perjudicial que ocurre a dosis normales de un fármaco. Diferente al efecto secundario, que puede o no ser dañino.",
    ejemplo: "La hemorragia gastrointestinal es un efecto adverso conocido de los antiinflamatorios no esteroideos.",
    relacionadas: ["farmaco", "alergia", "sobredosis"],
  },
  alergia: {
    titulo: "Alergia",
    categoria: "farmacologia",
    definicion: "Reacción inmunológica exagerada del organismo ante una sustancia (alérgeno) normalmente inocua. En el contexto farmacológico puede ser leve (urticaria) o grave (anafilaxia).",
    ejemplo: "La alergia a la penicilina es una de las alergias a fármacos más frecuentes.",
    relacionadas: ["efecto-adverso", "anafilaxia", "farmaco"],
  },
  anafilaxia: {
    titulo: "Anafilaxia",
    categoria: "farmacologia",
    definicion: "Reacción alérgica sistémica grave y de inicio rápido que puede ser potencialmente mortal. Se manifiesta con hipotensión, broncoespasmo y urticaria.",
    ejemplo: "La adrenalina intramuscular es el tratamiento de primera línea en la anafilaxia.",
    relacionadas: ["alergia", "efecto-adverso", "hipotension"],
  },
  antibiotico: {
    titulo: "Antibiótico",
    categoria: "farmacologia",
    definicion: "Fármaco utilizado para tratar infecciones causadas por bacterias. Actúa inhibiendo el crecimiento bacteriano (bacteriostático) o destruyendo las bacterias (bactericida).",
    ejemplo: "La amoxicilina es un antibiótico de amplio espectro del grupo de las penicilinas.",
    relacionadas: ["farmaco", "bacteria", "resistencia-antibiotica"],
  },
  "resistencia-antibiotica": {
    titulo: "Resistencia antibiótica",
    categoria: "farmacologia",
    definicion: "Capacidad que adquieren las bacterias para sobrevivir a la acción de un antibiótico que antes era efectivo contra ellas, frecuentemente por uso incorrecto o excesivo.",
    ejemplo: "El MRSA es un estafilococo con resistencia a la meticilina y es un problema de salud pública global.",
    relacionadas: ["antibiotico", "bacteria"],
  },
  antipiretico: {
    titulo: "Antipirético",
    categoria: "farmacologia",
    definicion: "Fármaco que reduce la fiebre al actuar sobre el centro termorregulador del hipotálamo.",
    ejemplo: "El paracetamol e ibuprofeno son los antipiréticos más utilizados en adultos y niños.",
    relacionadas: ["fiebre", "farmaco", "analgesico"],
  },
  analgesico: {
    titulo: "Analgésico",
    categoria: "farmacologia",
    definicion: "Fármaco que alivia el dolor sin producir pérdida de consciencia. Se clasifican en no opioides (paracetamol, AINEs) y opioides (morfina, tramadol).",
    ejemplo: "El tramadol es un analgésico opioide débil usado en dolor moderado a severo.",
    relacionadas: ["antipiretico", "farmaco", "dolor"],
  },

  // ── SIGNOS VITALES Y VALORACIÓN ───────────────────────────
  temperatura: {
    titulo: "Temperatura corporal",
    categoria: "signos",
    definicion: "Medida del calor del cuerpo generado por el metabolismo. El rango normal en adultos es de 36.5 °C a 37.5 °C.",
    ejemplo: "Se considera fiebre cuando la temperatura axilar supera los 38 °C.",
    relacionadas: ["fiebre", "hipotermia", "homeostasis"],
  },
  fiebre: {
    titulo: "Fiebre",
    categoria: "signos",
    definicion: "Elevación de la temperatura corporal por encima de 38 °C como respuesta del organismo ante una infección, inflamación u otras causas.",
    ejemplo: "La fiebre mayor de 40 °C (hiperpirexia) puede ser peligrosa y requiere atención urgente.",
    relacionadas: ["temperatura", "antipiretico", "infeccion"],
  },
  hipotermia: {
    titulo: "Hipotermia",
    categoria: "signos",
    definicion: "Temperatura corporal central por debajo de 35 °C. Puede ocurrir por exposición al frío, inmersión en agua fría o patologías sistémicas.",
    ejemplo: "En hipotermia severa (< 28 °C) puede aparecer paro cardíaco.",
    relacionadas: ["temperatura", "fiebre"],
  },
  glucemia: {
    titulo: "Glucemia",
    categoria: "signos",
    definicion: "Concentración de glucosa en la sangre. El rango normal en ayunas es de 70 a 100 mg/dL.",
    ejemplo: "Una glucemia en ayunas mayor de 126 mg/dL en dos ocasiones es criterio diagnóstico de diabetes.",
    relacionadas: ["hipoglucemia", "hiperglucemia", "insulina"],
  },
  hipoglucemia: {
    titulo: "Hipoglucemia",
    categoria: "signos",
    definicion: "Nivel de glucosa en sangre por debajo de 70 mg/dL. Puede causar mareos, sudoración, confusión y pérdida de consciencia.",
    ejemplo: "Un paciente diabético que no come tras inyectarse insulina puede sufrir hipoglucemia.",
    relacionadas: ["glucemia", "hiperglucemia", "insulina"],
  },
  hiperglucemia: {
    titulo: "Hiperglucemia",
    categoria: "signos",
    definicion: "Nivel elevado de glucosa en sangre, por encima de 130 mg/dL en ayunas. Característica de la diabetes mellitus no controlada.",
    ejemplo: "La poliuria y polidipsia son síntomas clásicos de hiperglucemia.",
    relacionadas: ["glucemia", "hipoglucemia", "diabetes"],
  },
  dolor: {
    titulo: "Dolor",
    categoria: "signos",
    definicion: "Experiencia sensorial y emocional desagradable asociada o descrita en términos de daño tisular real o potencial. Se considera el quinto signo vital.",
    ejemplo: "La escala EVA (1-10) se usa para cuantificar la intensidad del dolor del paciente.",
    relacionadas: ["analgesico", "escala-dolor"],
  },
  "escala-dolor": {
    titulo: "Escala del dolor (EVA)",
    categoria: "signos",
    definicion: "Herramienta de valoración del dolor que usa una escala numérica del 0 al 10, donde 0 es ausencia de dolor y 10 el peor dolor imaginable.",
    ejemplo: "Un paciente postoperatorio refiere dolor EVA 8, lo que indica un dolor severo que requiere analgesia.",
    relacionadas: ["dolor", "analgesico"],
  },

  // ── PROCEDIMIENTOS DE ENFERMERÍA ─────────────────────────
  "via-venosa": {
    titulo: "Vía venosa periférica",
    categoria: "procedimientos",
    definicion: "Catéter de corta longitud insertado en una vena periférica (generalmente del antebrazo o dorso de la mano) para administrar medicamentos, fluidos o extraer muestras.",
    ejemplo: "Antes de administrar antibiótico IV, la enfermera canaliza una vía venosa periférica en el antebrazo.",
    relacionadas: ["farmaco", "via-administracion", "flebitis"],
  },
  flebitis: {
    titulo: "Flebitis",
    categoria: "procedimientos",
    definicion: "Inflamación de la pared de una vena, frecuente como complicación de la canalización de una vía venosa. Se manifiesta con enrojecimiento, calor y dolor en el trayecto venoso.",
    ejemplo: "Se retiró la vía venosa al detectar signos de flebitis grado II en el dorso de la mano.",
    relacionadas: ["via-venosa", "infeccion"],
  },
  sondaje: {
    titulo: "Sondaje vesical",
    categoria: "procedimientos",
    definicion: "Inserción de una sonda a través de la uretra hasta la vejiga para drenar orina. Puede ser temporal (catéter intermitente) o permanente (sonda Foley).",
    ejemplo: "Se realizó sondaje vesical para medir la diuresis horaria en el paciente crítico.",
    relacionadas: ["diuresis", "infeccion-urinaria"],
  },
  diuresis: {
    titulo: "Diuresis",
    categoria: "procedimientos",
    definicion: "Volumen de orina producido en un período de tiempo. El rango normal en adultos es de 0.5 a 1 mL/kg/hora, aproximadamente 800-2000 mL al día.",
    ejemplo: "Una diuresis menor de 0.5 mL/kg/hora durante 6 horas es criterio de lesión renal aguda.",
    relacionadas: ["sondaje", "balance-hidrico"],
  },
  "balance-hidrico": {
    titulo: "Balance hídrico",
    categoria: "procedimientos",
    definicion: "Diferencia entre el total de líquidos que ingresan al organismo (ingesta oral, IV) y los que egresan (orina, sudor, heces, respiración) en un período de tiempo.",
    ejemplo: "Un balance hídrico positivo de +1500 mL puede indicar retención de líquidos.",
    relacionadas: ["diuresis", "edema"],
  },
  "signos-vitales": {
    titulo: "Signos vitales",
    categoria: "procedimientos",
    definicion: "Parámetros fisiológicos que reflejan el estado de las funciones vitales del paciente: temperatura, frecuencia cardíaca, frecuencia respiratoria, presión arterial y saturación de oxígeno.",
    ejemplo: "La enfermera toma los signos vitales cada 4 horas para monitorear la evolución del paciente.",
    relacionadas: ["temperatura", "frecuencia-cardiaca", "frecuencia-respiratoria", "presion-arterial", "saturacion"],
  },
  asepsia: {
    titulo: "Asepsia",
    categoria: "procedimientos",
    definicion: "Conjunto de medidas y procedimientos para prevenir la presencia de microorganismos patógenos en un área, material o tejido.",
    ejemplo: "La técnica aséptica es obligatoria al canalizar una vía venosa o realizar una cura.",
    relacionadas: ["antiseptico", "esterilizacion", "infeccion"],
  },
  antiseptico: {
    titulo: "Antiséptico",
    categoria: "procedimientos",
    definicion: "Sustancia química aplicada sobre tejidos vivos para eliminar o inhibir el crecimiento de microorganismos y prevenir la infección.",
    ejemplo: "La clorhexidina al 2% es el antiséptico recomendado para la preparación de la piel antes de insertar un catéter.",
    relacionadas: ["asepsia", "desinfectante"],
  },
  desinfectante: {
    titulo: "Desinfectante",
    categoria: "procedimientos",
    definicion: "Agente químico que destruye microorganismos sobre superficies inanimadas. A diferencia del antiséptico, NO se aplica en tejidos vivos.",
    ejemplo: "El hipoclorito de sodio (lejía) es un desinfectante usado para superficies hospitalarias.",
    relacionadas: ["antiseptico", "asepsia", "esterilizacion"],
  },
  esterilizacion: {
    titulo: "Esterilización",
    categoria: "procedimientos",
    definicion: "Proceso que elimina todas las formas de vida microbiana, incluyendo esporas, de un objeto o superficie. Es el nivel más alto de descontaminación.",
    ejemplo: "El instrumental quirúrgico se esteriliza en autoclave a 121 °C con vapor a presión.",
    relacionadas: ["asepsia", "desinfectante"],
  },

  // ── PATOLOGÍA Y ENFERMEDAD ────────────────────────────────
  infeccion: {
    titulo: "Infección",
    categoria: "patologia",
    definicion: "Invasión y multiplicación de microorganismos patógenos (bacterias, virus, hongos, parásitos) en tejidos del huésped, produciendo daño y respuesta inflamatoria.",
    ejemplo: "Una herida quirúrgica infectada presenta calor, rubor, tumor, dolor y supuración.",
    relacionadas: ["bacteria", "virus", "fiebre", "antibiotico"],
  },
  bacteria: {
    titulo: "Bacteria",
    categoria: "patologia",
    definicion: "Microorganismo unicelular procariota que puede ser patógeno o parte de la flora normal. Se clasifica en Gram positivas y Gram negativas según su pared celular.",
    ejemplo: "Streptococcus pneumoniae es la bacteria más frecuente en la neumonía adquirida en la comunidad.",
    relacionadas: ["infeccion", "antibiotico", "virus"],
  },
  virus: {
    titulo: "Virus",
    categoria: "patologia",
    definicion: "Agente infeccioso de tamaño submicroscópico que solo puede replicarse dentro de células huésped. No son sensibles a antibióticos, sino a antivirales.",
    ejemplo: "El virus de la influenza causa la gripe estacional y puede provocar complicaciones graves.",
    relacionadas: ["bacteria", "infeccion", "vacuna"],
  },
  vacuna: {
    titulo: "Vacuna",
    categoria: "patologia",
    definicion: "Preparación biológica que induce inmunidad activa frente a una enfermedad, estimulando al sistema inmune para producir anticuerpos específicos.",
    ejemplo: "La vacuna contra el tétanos se administra en tres dosis y requiere refuerzos cada 10 años.",
    relacionadas: ["inmunidad", "anticuerpo", "virus"],
  },
  inmunidad: {
    titulo: "Inmunidad",
    categoria: "patologia",
    definicion: "Capacidad del organismo para resistir o combatir enfermedades infecciosas y otras agresiones. Puede ser innata (inespecífica) o adaptativa (específica).",
    ejemplo: "La inmunidad de grupo se logra cuando una proporción suficiente de la población está inmunizada.",
    relacionadas: ["vacuna", "anticuerpo", "sistema-inmune"],
  },
  anticuerpo: {
    titulo: "Anticuerpo",
    categoria: "patologia",
    definicion: "Proteína producida por los linfocitos B en respuesta a un antígeno específico. Se une al antígeno para neutralizarlo o facilitar su destrucción.",
    ejemplo: "Los anticuerpos IgE están elevados en personas con alergias.",
    relacionadas: ["inmunidad", "vacuna", "alergia"],
  },
  edema: {
    titulo: "Edema",
    categoria: "patologia",
    definicion: "Acumulación anormal de líquido en el espacio intersticial de los tejidos, que provoca inflamación visible o palpable.",
    ejemplo: "El edema de tobillos bilateral en un paciente puede indicar insuficiencia cardíaca.",
    relacionadas: ["balance-hidrico", "inflamacion"],
  },
  inflamacion: {
    titulo: "Inflamación",
    categoria: "patologia",
    definicion: "Respuesta fisiológica de defensa del organismo ante una lesión, infección o irritante. Se caracteriza por rubor, calor, tumor (hinchazón), dolor y pérdida de función.",
    ejemplo: "La inflamación aguda de una articulación (artritis aguda) produce enrojecimiento y limitación del movimiento.",
    relacionadas: ["infeccion", "edema", "dolor"],
  },
  diabetes: {
    titulo: "Diabetes mellitus",
    categoria: "patologia",
    definicion: "Enfermedad crónica caracterizada por hiperglucemia sostenida debida a una deficiencia de insulina (tipo 1), resistencia a la insulina (tipo 2) o ambas.",
    ejemplo: "Un paciente con diabetes tipo 2 mal controlada puede desarrollar neuropatía, retinopatía y nefropatía.",
    relacionadas: ["glucemia", "hiperglucemia", "insulina"],
  },
  insulina: {
    titulo: "Insulina",
    categoria: "patologia",
    definicion: "Hormona producida por las células beta del páncreas que facilita la entrada de glucosa a las células y regula la glucemia.",
    ejemplo: "Los pacientes con diabetes tipo 1 dependen de la insulina exógena para sobrevivir.",
    relacionadas: ["diabetes", "glucemia", "hipoglucemia"],
  },
  "infeccion-urinaria": {
    titulo: "Infección urinaria (ITU)",
    categoria: "patologia",
    definicion: "Infección bacteriana del tracto urinario (uretra, vejiga, uréteres o riñones). Es más frecuente en mujeres. Se manifiesta con disuria, polaquiuria y urgencia miccional.",
    ejemplo: "La E. coli es la bacteria responsable de más del 80% de las infecciones urinarias no complicadas.",
    relacionadas: ["infeccion", "bacteria", "sondaje"],
  },


  // ── TÉRMINOS ADICIONALES ──────────────────────────────────
  salud: {
    titulo: "Salud",
    categoria: "anatomia",
    definicion: "Estado de completo bienestar físico, mental y social, y no meramente la ausencia de enfermedad o dolencia. Definición de la Organización Mundial de la Salud (OMS, 1948).",
    ejemplo: "La promoción de la salud busca que las personas adopten estilos de vida saludables, no solo tratar enfermedades.",
    relacionadas: ["bienestar", "homeostasis", "enfermeria"],
  },
  enfermeria: {
    titulo: "Enfermería",
    categoria: "procedimientos",
    definicion: "Disciplina científica y humanística que se ocupa del cuidado integral de la salud de las personas, familias y comunidades, promoviendo el bienestar, previniendo la enfermedad y acompañando el proceso de recuperación.",
    ejemplo: "La enfermería moderna combina conocimiento clínico, pensamiento crítico y competencia humana en cada intervención.",
    relacionadas: ["salud", "bienestar", "signos-vitales"],
  },
  pulmones: {
    titulo: "Pulmones",
    categoria: "respiratorio",
    definicion: "Órganos pares del sistema respiratorio encargados del intercambio gaseoso entre el aire y la sangre. El pulmón derecho tiene tres lóbulos y el izquierdo dos, siendo este último ligeramente más pequeño para alojar al corazón.",
    ejemplo: "Una radiografía de tórax permite evaluar el tamaño, forma y densidad de los pulmones.",
    relacionadas: ["alveolo", "bronquio", "saturacion", "disnea"],
  },
  ojos: {
    titulo: "Ojos",
    categoria: "anatomia",
    definicion: "Órganos sensoriales de la visión. Convierten la luz en señales nerviosas que el cerebro interpreta como imágenes. Están protegidos por los párpados, las pestañas y el líquido lagrimal.",
    ejemplo: "La exploración de los ojos incluye evaluar agudeza visual, reflejos pupilares y fondo de ojo.",
    relacionadas: ["cerebro", "neurona"],
  },
  bienestar: {
    titulo: "Bienestar",
    categoria: "anatomia",
    definicion: "Estado dinámico en el que el individuo experimenta satisfacción física, emocional y social. Componente esencial del concepto de salud según la OMS.",
    ejemplo: "El bienestar del paciente incluye no solo su estado clínico, sino también su comodidad y estado emocional.",
    relacionadas: ["salud", "homeostasis"],
  },
  cefalea: {
    titulo: "Cefalea",
    categoria: "patologia",
    definicion: "Término médico para el dolor de cabeza. Puede ser primaria (migraña, cefalea tensional) cuando el dolor es la enfermedad en sí, o secundaria cuando es síntoma de otra patología.",
    ejemplo: "Una cefalea súbita de gran intensidad descrita como 'la peor de mi vida' puede indicar hemorragia subaracnoidea.",
    relacionadas: ["dolor", "neurona", "cerebro", "escala-dolor"],
  },
  caudal: {
    titulo: "Caudal",
    categoria: "procedimientos",
    definicion: "En contexto clínico, se refiere al volumen de fluido que pasa por una vía o conducto por unidad de tiempo. En venoclisis, el caudal (gotas por minuto o mL/hora) determina la velocidad de infusión.",
    ejemplo: "Se ajustó el caudal de la venoclisis a 40 gotas por minuto para administrar el litro de solución en 6 horas.",
    relacionadas: ["via-venosa", "balance-hidrico", "diuresis"],
  },
  pirexia: {
    titulo: "Pirexia",
    categoria: "signos",
    definicion: "Sinónimo médico de fiebre. Elevación de la temperatura corporal por encima de 38 °C como respuesta del organismo. El término proviene del griego 'pyr' (fuego).",
    ejemplo: "El médico registró 'pirexia de 38.8 °C' en la nota clínica, indicando la necesidad de antipirético.",
    relacionadas: ["fiebre", "temperatura", "antipiretico", "infeccion"],
  },

  // ── EASTER EGGS ───────────────────────────────────────────
  medusas: {
    titulo: "Medusas 🪼",
    categoria: null,
    definicion: "Animal marino invertebrado, transparente y gelatinoso, que en una fase de su vida tiene forma de campana o sombrilla provista de tentáculos. Algunas especies son biológicamente inmortales.",
    ejemplo: "Definitivamente esto está aquí. Es un easter egg. La Turritopsis dohrnii puede revertir su ciclo vital.",
    relacionadas: ["homeostasis"],
  },
  mermelada: {
    titulo: "Mermelada 🍓",
    categoria: null,
    definicion: "¡Óyeme! ¿En serio? Ponte a estudiar y deja de distraerte.",
    ejemplo: "Tú, buscando esta palabra en lugar de repasar los signos vitales.",
    relacionadas: ["procrastinacion", "ADHD", "flojera"],
  },
};
